plugins: musicbrainz
directory: /music # Mapped in docker-compose
import:
  copy: no
  move: yes
  resume: no
  duplicate_action: remove
paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $albumartist/$album%aunique{}/$title
match:
  strong_rec_thresh: 0.10
  max_rec:
    missing_tracks: low
musicbrainz:
  searchlimit: 20            # Recommendation from: https://github.com/kernitus/beets-oldestdate
  extra_tags:                # Enable improved MediaBrainz queries from tags.
    [
      catalognum,
      country,
      label,
      media,
      year
    ]
